name: Deploy Admin Dashboard

on:
push:
branches:
- develop

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Deploy to EC2
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USERNAME }}
      key: ${{ secrets.EC2_SSH_KEY }}
      port: 22
      script: |
        set -e

        echo "Go to project directory"
        cd /home/ubuntu/apps/social_admin

        echo "Pull latest code"
        git pull origin develop

        echo "Build and restart container"
        docker compose down
        docker compose up -d --build

        echo "Cleanup old images"
        docker image prune -f

        echo "Show running containers"
        docker compose ps
